name: Compile bot with make CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - arch: aarch64
            distro: ubuntu_latest
          - arch: armv7
            distro: ubuntu_latest

    steps:
      - uses: actions/checkout@v3
      - uses: uraimo/run-on-arch-action@v2
        name: Build artifact
        id: build
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          githubToken: ${{ github.token }}
          env: |
            BIN: bot-${{ matrix.arch }}-${{ matrix.distro }}
          shell: /bin/sh
          install: |
            apt install git binutils make clang
          run: |
            uname -a
            bash ./configure.sh
            make
      #    - name: ./configure
      #      run: bash ./configure.sh
      #    - name: make
      #      run: make
